apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: health-103

resources:
#  - project.yaml
#  - rolebindings.yaml
  - health-103-deploy.yaml
  - health-103-service.yaml
  - health-103-route.yaml
